name: Checks
on:
    pull_request:
    push:
        branches:
            - "master"
            - "v[0-9]"
jobs:
    checks:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
            -
                name: Install dependencies
                run: composer install --no-progress --prefer-dist --no-interaction

            -
                name: Run checks
                run: composer check

    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.1', '8.2', '8.3' ]
                doctrine-version: [ '^2.19', '^3.2' ]
                dependency-version: [ prefer-lowest, prefer-stable ]
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -
                name: Install dependencies
                run: composer update --no-progress --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            -
                name: Install correct version of Doctrine
                run: composer update --no-progress --${{ matrix.dependency-version }} --prefer-dist --no-interaction --with-all-dependencies doctrine/orm:${{ matrix.doctrine-version }}
            -
                name: Run tests
                run: composer check:tests
